swagger: "2.0"
info:
  version: "1.0"
  title: "Hello World API"
paths:
  /hello/user:
    get:
      description: Returns a greeting to the user!
      parameters:
        - name: user
          in: path
          type: string
          required: true
          description: The name of the user to greet.
          example: world
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: string
        400:
          description: Invalid characters in "user" were provided.

  /goodbye/user:
    get:
      description: Returns a farewall to the user!
      parameters:
        - name: user
          in: path
          type: string
          required: true
          description: The name of the user.
          example: world
      responses:
        200:
          description: Returns the farewall.
          schema:
            type: string
        400:
          description: Invalid characters in "user" were provided.

  /aurevoir/user:
    get:
      description: Returns a au revoir to the user!
      parameters:
        - name: user
          in: path
          type: string
          required: true
          description: The name of the user.
          example: world
      responses:
        200:
          description: Returns the "see ya later".
          schema:
            type: string
        400:
          description: Invalid characters in "user" were provided.
